# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: EmployeeStatusLog

# Model Form Field configuration
form: @/plugins/cn/statusboard/models/employeestatuslog/fields.yaml

# Model Class name
modelClass: Cn\StatusBoard\Models\EmployeeStatusLog

# Default redirect location
defaultRedirect: cn/statusboard/employeestatuslogs

# Create page
create:
    title: Create EmployeeStatusLogs
    redirect: cn/statusboard/employeestatuslogs/update/:id
    redirectClose: cn/statusboard/employeestatuslogs

# Update page
update:
    title: Edit EmployeeStatusLogs
    redirect: cn/statusboard/employeestatuslogs
    redirectClose: cn/statusboard/employeestatuslogs

# Preview page
preview:
    title: Preview EmployeeStatusLogs