# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Employee

# Model Form Field configuration
form: @/plugins/cn/statusboard/models/employee/fields.yaml

# Model Class name
modelClass: Cn\StatusBoard\Models\Employee

# Default redirect location
defaultRedirect: cn/statusboard/employees

# Create page
create:
    title: Create Employees
    redirect: cn/statusboard/employees/update/:id
    redirectClose: cn/statusboard/employees

# Update page
update:
    title: Edit Employees
    redirect: cn/statusboard/employees
    redirectClose: cn/statusboard/employees

# Preview page
preview:
    title: Preview Employees